INSERT INTO TABLA VALUES (1, 1, 1, 1);
SELECT * FROM TABLA;
DELETE FROM TABLA WHERE ID_TABLA = 1;
UPDATE TABLA SET CAMPO1 = VALOR1 WHERE ID_TABLA = 1;

ALTER TABLE Orders
ADD CONSTRAINT FK_PersonOrder
FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);